/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthRedirect: typeof import('./src/components/account/auth-redirect.vue')['default']
    'Cd.about': typeof import('./src/components/about/cd.about.vue')['default']
    'Cd.contact': typeof import('./src/components/contact/cd.contact.vue')['default']
    'Cd.contribute': typeof import('./src/components/contribute/cd.contribute.vue')['default']
    'Cd.dataset': typeof import('./src/components/dataset/cd.dataset.vue')['default']
    'Cd.datasetHtml': typeof import('./src/components/dataset/cd.dataset-html.vue')['default']
    'Cd.featuredDatasets': typeof import('./src/components/home/cd.featured-datasets.vue')['default']
    'Cd.footer': typeof import('./src/components/base/cd.footer.vue')['default']
    'Cd.home': typeof import('./src/components/home/cd.home.vue')['default']
    'Cd.homeSearch': typeof import('./src/components/home/cd.home-search.vue')['default']
    'Cd.login': typeof import('./src/components/account/cd.login.vue')['default']
    'Cd.registerDataset': typeof import('./src/components/register/cd.register-dataset.vue')['default']
    'Cd.search': typeof import('./src/components/search/cd.search.vue')['default']
    'Cd.searchResults': typeof import('./src/components/search-results/cd.search-results.vue')['default']
    'Cd.spatialCoverageMap': typeof import('./src/components/search-results/cd.spatial-coverage-map.vue')['default']
    'Cd.submissions': typeof import('./src/components/submissions/cd.submissions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
