declare const VITE_APP_NAME: string;
declare const VITE_APP_URL: string;
declare const VITE_APP_API_URL: string;
declare const VITE_APP_LOGIN_URL: string;
declare const VITE_APP_HEAP_ANALYTICS_APP_ID: string;
declare const VITE_APP_GOOGLE_MAPS_API_KEY: string;
declare const VITE_APP_SUPPORT_EMAIL: string;
declare const VITE_APP_CLIENT_ID: string;
declare const APP_VERSION: string;
