FROM node:14 as build-stage
WORKDIR /app
COPY frontend/package*.json ./
RUN npm i @cznethub/cznet-vue-core --legacy-peer-deps
RUN npm install --legacy-peer-deps
COPY ./frontend .
RUN npm run build-prod

FROM nginx:1.23.1 as production-stage
WORKDIR /app
COPY --from=build-stage /app/dist /app
COPY frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 5003
